### ISSUE TITLE
Require help with non-existent config key error

### ISSUE THREAD

**Issue by zuroh** [dvlab-research/Entity#1]
Hi there, thanks for your work! It looks very interesting and i would like to test it out, however I keep running into the same problem when testing the visualization script and wondering if you could help me out. 

Steps I did:

1. Build detectron2 from source using the same commit version and pytorch version in your README
2. clone this repo into projects/EntitySeg
3. Download the pretrained R50.pth model
4. Install the panopticapi library
5. Run python3 projects/EntitySeg/demo_result_and_vis.py --config-file projects/EntitySeg/configs/entity_swin_lw7_1x.yaml --input data/input/*.jpg --output data/output MODEL.WEIGHTS data/pretrained_model/R_50.pth MODEL.CONDINST.MASK_BRANCH.USE_MASK_RESCORE "True"

Below is my error:
![error](https://user-images.githubusercontent.com/32504839/127797967-6d0ff679-3ef3-4fcb-b5fb-4e27a109a5d7.PNG)

Any help is greatly appreciated. Thank you!

**Comment by qqlu** [comment]
Hi,

I am sorry that I missed this key in the Github code. You can add one line code "cfg.SOLVER.OPTIMIZER = "sgd"" in EntitySeg/entityseg/config.py.  I also push it. Please check.

**Comment by zuroh** [comment]
Thanks for the response, you might want to add 
`cfg.TEST.CLASS_AGNOSTIC = True` 
to config.py as well as that was also giving me config errors.

**Comment by qqlu** [comment]
Thanks very much for helping us checking the code. We have updated it.

**Comment by zuroh** [comment]
visualization script works now. Thanks again for your great work! Closing this issue.
