### ISSUE TITLE
"High Quality Segmentation for Ultra High-resolution Images" code release

### ISSUE THREAD

**Issue by VolodymyrAhafonov** [dvlab-research/Entity#12]
Hello guys,
I've read "High Quality Segmentation for Ultra High-resolution Images" recently. Great work!
I am very excited about this paper. 
When do you plan to release code for this paper?

Thanks in advance.

**Comment by qqlu** [comment]
Hi, thanks for your interest in our paper. 

Our code is originally based on CascadePSP. We are moving them to detectron2 for convenient usage with existing instance/panoptic/entity segmentation methods. 

We will release our code in the next two months.
