### ISSUE TITLE
Where is the code of the article “High Quality Segmentation for Ultra High-resolution Images ”?

### ISSUE THREAD

**Issue by Joysheng** [dvlab-research/Entity#14]

**Comment by qqlu** [comment]
@Joysheng Hi, Tiancheng, could you help solve this issue?

**Comment by tcShen** [comment]
Hi, thanks for your interest in our paper.

Our code is originally based on CascadePSP. We are moving it to detectron2 for convenient usage and code style consistency.

We will release our code within a month or two. Thanks.

**Comment by zhangxiaobaibai** [comment]
Hi.
It seems that two months have gone since you reply that you would release your code. Can you give a relatively accurate time? Thanks

> Hi, thanks for your interest in our paper.
> 
> Our code is originally based on CascadePSP. We are moving it to detectron2 for convenient usage and code style consistency.
> 
> We will release our code within a month or two. Thanks.

**Comment by tcShen** [comment]
The code is released.  Sorry for being several weeks late. Thanks.
