### ISSUE TITLE
Graphics card requirements

### ISSUE THREAD

**Issue by KevinBanksB** [dvlab-research/Entity#17]
Hello, you‘ve mentioned at the beginning of your abstract that the traditional approach have the problem of balancing computational cost and computational time. So I want to know how much graphics card memory and computing time your method needs when conducting 2K or 6K images？And what kind of graphics card we need to run this code? Thank you.

**Comment by tcShen** [comment]
Thanks for your question.
1. In our paper, "Common strategies, such as down-sampling, patch cropping, and cascade model, cannot address well the balance issue between accuracy and computation cost" means down-sampling, patch cropping, and cascade in previous methods are considered as compromise strategies. But our CRM continuously aligns feature and generate high-resolution results pixel by pixel. It can solve the task in a more flexible, elegant, and efficient way.
2. For training, two 2080 Ti are enough. For inference, I use 3090 or A100. If your GPU memory is limited, you can reduce the inference chunk size. Another way is to dynamically extract the image feature through R-50 based on the receptive field size. 
Thanks.

**Comment by KevinBanksB** [comment]
Awesome！Thank you very much for your prompt reply.
